# Site
name: "Fawn's Corner"
title: "Fawn"
description: "raynna's little corner of the internet"
logo: 'assets/images/iconlogo'
favicon: 'assets/images/favicon.png'
baseurl: /fawn
google_analytics: 'G-VK7GP3QCYJ'
disqus: 'demowebsite'
mailchimp-list: '/'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  raynna:
    name: Raynna
    display_name: Fawn
    gravatar: 51d47b4ab427650f79304e7aa7ca064f6d2b18d40c650e0a612f8b122bab4b0e
    email: deerdoesmail@gmail.com
    web: rayn-na.github.io/fawn
    twitter: https://twitter.com/digitalraindeer
    description: "Um, y'know!"


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
